version: 0.2

env:
  variables:
    DOTNET_FRAMEWORK: 4.5

phases:
  pre_build:
    commands:
      dotnet restore MyDemoApp/MyDemoApp/MyDemoApp.csproj
  build:
    commands:
      dotnet publish -c release MyDemoApp/MyDemoApp/MyDemoApp.csproj -o ./publish
artifacts:
  files:
    - installScripts/**/*
    - appspec.yml
    - ./publish/**/*
