version: 0.2

env:
  variables:
    PROJECT: MyDemoApp
    DOTNET_FRAMEWORK: 4.5

phases: 
  install:
    commands:
      - nuget install MyDemoApp/MyDemoApp/packages.config
  pre_build:
    commands:
      - nuget restore MyDemoApp/MyDemoApp.sln
  build:
    commands:
      - msbuild $env:PROJECT/$env:PROJECT/$env:PROJECT.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=./publish
artifacts: 
    files:     
    - installScripts/**/*
    - appspec.yml
    - ./publish/**/*
    - **/*
